#!C:\Users\s1294807\OneDrive - Syngenta\Projetos pessoais - Kauan\Insider Cluster\Loyalty-program\loyalty310\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
